### ISSUE TITLE
Exception when using jackson-databind 2.11.0

### ISSUE THREAD

**Issue by bspammer** [messagebird/java-rest-api#109]
Steps to reproduce:

1. Change the version of `jackson-databind` to `2.11.0` in `pom.xml`
2. Run tests

```
com.messagebird.exceptions.GeneralException: 
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.messagebird.objects.MClassType`, problem: argument type mismatch
 at [Source: (String)"{"id":"92e18ce7f8a348d39d7d0ebb43dcda7e","href":"https://rest.messagebird.com/messages/92e18ce7f8a348d39d7d0ebb43dcda7e","direction":"mt","type":"sms","originator":"+12345678901234567","body":"Body test message Über € 1111111111","reference":null,"validity":null,"gateway":10,"typeDetails":{},"datacoding":"plain","mclass":1,"scheduledDatetime":null,"createdDatetime":"2020-05-19T17:29:57+00:00","recipients":{"totalCount":1,"totalSentCount":1,"totalDeliveredCount":0,"totalDeliveryFailedCount":0,"it"[truncated 115 chars]; line: 1, column: 324] (through reference chain: com.messagebird.objects.MessageResponse["mclass"])
	at com.messagebird.MessageBirdClientTest.testSendMessageTestOriginatorLength(MessageBirdClientTest.java:194)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: 
Cannot construct instance of `com.messagebird.objects.MClassType`, problem: argument type mismatch
 at [Source: (String)"{"id":"92e18ce7f8a348d39d7d0ebb43dcda7e","href":"https://rest.messagebird.com/messages/92e18ce7f8a348d39d7d0ebb43dcda7e","direction":"mt","type":"sms","originator":"+12345678901234567","body":"Body test message Über € 1111111111","reference":null,"validity":null,"gateway":10,"typeDetails":{},"datacoding":"plain","mclass":1,"scheduledDatetime":null,"createdDatetime":"2020-05-19T17:29:57+00:00","recipients":{"totalCount":1,"totalSentCount":1,"totalDeliveredCount":0,"totalDeliveryFailedCount":0,"it"[truncated 115 chars]; line: 1, column: 324] (through reference chain: com.messagebird.objects.MessageResponse["mclass"])
	at com.messagebird.MessageBirdClientTest.testSendMessageTestOriginatorLength(MessageBirdClientTest.java:194)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at com.messagebird.MessageBirdClientTest.testSendMessageTestOriginatorLength(MessageBirdClientTest.java:194)
```

**Comment by denizkilic** [comment]
Hi @bspammer,
We will consider updating lib versions that you want and investigate the bug. For a quick solution, if you delete ` @JsonCreator` on MClassType.java tests will be passed successfully.

**Comment by samdohrey** [comment]
Sadly the same error occurs running the latest Spring Boot libraries e.g. 2.3.0.RELEASE

Will 100% need fixing as Spring is an extremely popular framework with Enterprise

We are trying to update our servers to the latest versions, sadly the error showed when sending using:

Class: MessageBirdClient
Method:
_public MessageResponse sendMessage(final String originator, final String body, final List<BigInteger> recipients)_

The SMS gets sent after a delay but the application throws a ValueInstantiationException error.

Spring 2.2.0.RELEASE is fine. So is 2.1.7.RELEASE

Cheers,

**Comment by samdohrey** [comment]
Sorry I should have said. The later Spring libraries use: jackson-databind 2.11.0

**Comment by olimpias** [comment]
Hi @samdohrey, thank you for reaching us. We will investigate the problem with @denizkilic  and come with a solution on the following days.

**Comment by denizkilic** [comment]
Hi @samdohrey, @bspammer 
Jackson library version was updated to 2.11.0 in the latest release (Release 3.0.13). We will be glad to encounter any issue if you have.

**Comment by bspammer** [comment]
Hi, thanks for this!
