### ISSUE TITLE
`com.messagebird.objects.MClassType`, problem: argument type mismatch

### ISSUE THREAD

**Issue by davidb-e4s** [messagebird/java-rest-api#112]
Using Kotlin 1.3.72
Spring boot 2.3.0.RELEASE
Jackson 2.11.0 (Being pulled in by SB)

Get the following when sending a message to message bird on the latest released version 

`com.messagebird.exceptions.GeneralException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.messagebird.objects.MClassType`, problem: argument type mismatch
 at [Source: (String)"{"id":"ba58e41ebf7849caa3ff785354b884aa","href":"mburl","direction":"mt","type":"sms","originator":"test co","body":"test body","reference":null,"validity":null,"gateway":10,"typeDetails":{},"datacoding":"plain","mclass":1,"scheduledDatetime":null,"createdDatetime":"2020-06-11T1"[truncated 236 chars]; line: 1, column: 443] (through reference chain: com.messagebird.objects.MessageResponse["mclass"])
	at com.messagebird.MessageBirdServiceImpl.getJsonData(MessageBirdServiceImpl.java:220)
	at com.messagebird.MessageBirdServiceImpl.sendPayLoad(MessageBirdServiceImpl.java:165)
	at com.messagebird.MessageBirdServiceImpl.sendPayLoad(MessageBirdServiceImpl.java:155)
	at com.messagebird.MessageBirdClient.sendMessage(MessageBirdClient.java:214)
	at co.uk.e4s.notification.service.processors.SMSProcessor.process(SMSProcessor.kt:42)
	at co.uk.e4s.notification.service.service.NotificationCreateService.process(NotificationCreateService.kt:49)
	at co.uk.e4s.notification.service.service.NotificationCreateService$$FastClassBySpringCGLIB$$c90d7639.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:118)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at co.uk.e4s.notification.service.service.NotificationCreateService$$EnhancerBySpringCGLIB$$b4e5496a.process(<generated>)
	at co.uk.e4s.notification.service.service.NotificationCreateService.process$default(NotificationCreateService.kt:30)
	at co.uk.e4s.notification.service.listeners.NotificationCreateEventListener.receive(NotificationCreateEventListener.kt:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.amqp.rabbit.listener.adapter.DelegatingInvocableHandler.invoke(DelegatingInvocableHandler.java:130)
	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:66)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:220)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:148)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:133)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1579)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1498)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1486)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1477)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1421)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:963)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by olimpias** [comment]
I will take a look at this problem in the evening. Thank you for reporting!

**Comment by olimpias** [comment]
Hi @davidb-e4s , I think you are using `v3.0.10` or lower version because the error logs that you shared, show that the exception happened at line 220. In new versions, in that line, we are creating the object mapper.(I don't expect to see any exception there) That is why I suspect that you are using the old version. Could you update to version `3.0.13`  ?
