### ISSUE TITLE
There is under JDK 12 code in allowPatchRequestsIfNeeded() method

### ISSUE THREAD

**Issue by ssk910** [messagebird/java-rest-api#168]
Hello.

First of all, I'm so appreciated for implement Partner Account API quickly.
But unfortunately, I have an issue with it.

A [`allowPatchRequestsIfNeeded()`](https://github.com/messagebird/java-rest-api/blob/220785e586eef63ac909c8e68bd50f8ec9099689/api/src/main/java/com/messagebird/MessageBirdServiceImpl.java#L464) method uses under `JDK 12` code.
It means your Java SDK supports for only under `JDK 12`.

I use `JDK 16` for my project. 
In my case, An example class `ExampleUpdateChildAccount` throws `java.lang.reflect.InaccessibleObjectException`.

**Error message:**
```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.String[] java.net.HttpURLConnection.methods accessible: module java.base does not "opens java.net" to unnamed module @548c4f57
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.messagebird.MessageBirdServiceImpl.allowPatchRequestsIfNeeded(MessageBirdServiceImpl.java:474)
	at com.messagebird.MessageBirdServiceImpl.doRequest(MessageBirdServiceImpl.java:374)
	at com.messagebird.MessageBirdServiceImpl.getJsonData(MessageBirdServiceImpl.java:263)
	at com.messagebird.MessageBirdServiceImpl.sendPayLoad(MessageBirdServiceImpl.java:217)
	at com.messagebird.MessageBirdServiceImpl.sendPayLoad(MessageBirdServiceImpl.java:207)
	at com.messagebird.MessageBirdClient.updateChildAccount(MessageBirdClient.java:2030)
	at ExampleUpdateChildAccount.main(ExampleUpdateChildAccount.java:20)
```

Is it ok with supporting for only under `JDK 12` users?

**Comment by denizkilic** [comment]
Hello @ssk910,
This issue will be solved in the next version which will be released in a couple of days.

**Comment by denizkilic** [comment]
Hi @ssk910,
This issue is ongoing in release 3.1.5, working on it. I will inform you when this is ready. Thank you.

**Comment by ssk910** [comment]
Hello @denizkilic,
Thank you for letting me know.
