### ISSUE TITLE
getVersion() fails if java.version is not properly set

### ISSUE THREAD

**Issue by epels** [messagebird/java-rest-api#30]
Some runtimes, like Android, do not properly set the `java.version` system property. This causes [`getVersion`](https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/MessageBirdServiceImpl.java#L226) to throw a `StringIndexOutOfBoundsException`:

```java
private double getVersion() {
        String version = System.getProperty("java.version");
        int pos = version.indexOf('.');
        pos = version.indexOf('.', pos + 1);
        return Double.parseDouble(version.substring(0, pos));
}
```

Trace:
```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107)
	at java.base/java.lang.String.substring(String.java:1873)
	at com.messagebird.MessageBirdServiceImpl.getVersion(MessageBirdServiceImpl.java:241)
	at com.messagebird.MessageBirdServiceImpl.getDateFormat(MessageBirdServiceImpl.java:226)
	at com.messagebird.MessageBirdServiceImpl.getConnection(MessageBirdServiceImpl.java:204)
	at com.messagebird.MessageBirdServiceImpl.getJsonData(MessageBirdServiceImpl.java:129)
	at com.messagebird.MessageBirdServiceImpl.sendPayLoad(MessageBirdServiceImpl.java:114)
	at com.messagebird.MessageBirdClient.sendMessage(MessageBirdClient.java:124)
	at com.messagebird.MessageBirdClientTest.testSendMessageWithoutVersion(MessageBirdClientTest.java:173)
```

**Comment by epels** [comment]
Resolved in [`v2.0.0`](https://mvnrepository.com/artifact/com.messagebird/messagebird-api/2.0.0).
